# Copyright (c) 2020-2029 GUARD <guard-project.eu>
# author: Alex Carrega <alessandro.carrega@cnit.it>

kafka:
  bootstrap-servers:
    - localhost:9092
  topic: network-data
  group-id: group_id
log:
  format: "%(message)s"
  level: INFO
