# Copyright (c) 2020-2029 GUARD <guard-project.eu>
# author: Alex Carrega <alessandro.carrega@cnit.it>

kafka:
  bootstrap-servers:
    - localhost:9092
  client-id: cnit_ml
  security-protocol: SSL
  ssl-cafile: keys/truststore.pem
  ssl-certfile: keys/keystore.pem
  topic: network-data
  group-id: group_id
log:
  format: "%(message)s"
  level: INFO
version: v3
sources:
  - 120.34.5.6
