# Copyright (c) 2020-2029 Alex Carrega <contact@alexcarrega.com>
# author: Alex Carrega <contact@alexcarrega.com>

port: 9999
debug: True
name: CNIT ML
description: CNIT Machine Learning Algorithm Controller.
commands:
  start:
    script: python deployment.py
    daemon: false
