# Copyright (c) 2020-2029 GUARD <guard-project.eu>
# author: Alex Carrega <alessandro.carrega@cnit.it>

port: 9999
debug: True
name: CNIT ML
description: CNIT Machine Learning Algorithm Controller.
commands:
  start:
    script: bash scripts/start.sh
    daemon: false
  stop:
    script: bash scripts/stop.sh
    daemon: false
  restart:
    script: bash scripts/restart.sh
    daemon: false
parameters:
  kafka-bootstrap-servers:
    source: config.yaml
    format: yaml
    xpath:
      - kafka
      - bootstrap-servers
  kafka-topic:
    source: config.yaml
    format: yaml
    xpath:
      - kafka
      - topic
